#!/usr/bin/env python3
"""Generates the Unicode script table used by the `UnicodeScripts` pre-tokenizer.

The source is `tokenizers/src/pre_tokenizers/unicode_scripts/scripts.rs` of the pinned
Hugging Face checkout, itself generated from the Unicode script data SentencePiece uses.
Reading it directly keeps the split boundaries identical to the reference for every scalar.

    python3 scripts/unicode_scripts.py --scripts-rs <checkout>/tokenizers/src/pre_tokenizers/unicode_scripts/scripts.rs

`fixed_script` (Hiragana/Katakana/U+30FC folded to Han, space treated as "any") is applied
while generating, so the runtime table is exactly what the pre-tokenizer compares.
"""
import argparse
import hashlib
import re
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "Sources/Tokenizers/Core/UnicodeScripts.generated.swift"
ARM = re.compile(r"^\s*0x([0-9A-Fa-f]+)(?:\.\.=0x([0-9A-Fa-f]+))?\s*=>\s*Script::(\w+),\s*$")

# `Any` is the implicit default arm and marks "belongs to every script"; `fixed_script` also
# maps the space character to it.
ANY = 0


def parse(path):
    text = path.read_text()
    body = text[text.index("pub fn get_script("):]
    body = body[: body.index("\n}")]
    names = {}
    entries = []
    for line in body.splitlines():
        match = ARM.match(line)
        if not match:
            continue
        start = int(match.group(1), 16)
        end = int(match.group(2), 16) if match.group(2) else start
        name = match.group(3)
        entries.append((start, end, name))
    # `fixed_script`: Hiragana and Katakana are treated as Han, U+30FC too, and the plain
    # space matches any script.
    folded = []
    for start, end, name in entries:
        if name in ("Hiragana", "Katakana"):
            name = "Han"
        folded.append((start, end, name))
    folded.append((0x30FC, 0x30FC, "Han"))
    folded.append((0x20, 0x20, "Any"))
    names = {"Any": ANY}
    for _, _, name in folded:
        names.setdefault(name, len(names))

    # Later arms win, matching the `match` fall-through of the folded additions above.
    table = {}
    for start, end, name in folded:
        for value in range(start, end + 1):
            table[value] = names[name]

    # A total partition of the scalar space: gaps between arms are the `_ => Script::Any`
    # default, so only the start of each run has to be stored.
    runs = []
    previous = None
    for value in range(0x110000):
        script = table.get(value, ANY)
        if script != previous:
            runs.append((value, script))
            previous = script
    return runs, names, hashlib.sha256(text.encode()).hexdigest()


def emit(runs, names, digest, source):
    lines = [
        "// Generated by scripts/unicode_scripts.py. Do not edit.",
        f"// Source: {source} (SHA-256 {digest}),",
        "// itself generated from the Unicode script data used by SentencePiece.",
        "// Hiragana, Katakana and U+30FC are folded to Han and U+0020 to `any`, as",
        "// `tokenizers::pre_tokenizers::unicode_scripts::fixed_script` does at runtime.",
        "",
        "/// Script identity of a Unicode scalar, as the `UnicodeScripts` pre-tokenizer sees it.",
        "enum UnicodeScriptTable {",
        f"    /// Scalars that belong to every script (the default, plus U+0020). {len(names)} scripts.",
        "    static let any: UInt8 = 0",
        "",
        "    /// Ascending run starts partitioning the whole scalar space; the script of a",
        "    /// scalar is `scripts[i]` for the last `starts[i]` that does not exceed it.",
        "    static let starts: [UInt32] = [",
    ]
    for chunk in range(0, len(runs), 8):
        lines.append("        " + " ".join(f"0x{v:05X}," for v, _ in runs[chunk : chunk + 8]))
    lines.append("    ]")
    lines.append("")
    lines.append("    static let scripts: [UInt8] = [")
    ids = [script for _, script in runs]
    for chunk in range(0, len(ids), 20):
        lines.append("        " + " ".join(f"{v}," for v in ids[chunk : chunk + 20]))
    lines.append("    ]")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scripts-rs", required=True)
    parser.add_argument("--out", default=str(OUTPUT))
    args = parser.parse_args()
    path = Path(args.scripts_rs)
    runs, names, digest = parse(path)
    source = "tokenizers/src/pre_tokenizers/unicode_scripts/scripts.rs"
    Path(args.out).write_text(emit(runs, names, digest, source))
    print(f"{len(runs)} runs, {len(names)} scripts -> {args.out}")


if __name__ == "__main__":
    main()
