#!/usr/bin/env python3
"""Generate the Unicode compatibility envelope from pinned UCD releases.

Usage: python3 scripts/unicode_compatibility.py --ucd-dir /path/to/ucd [--check]
The directory must contain <version>/UnicodeData.txt
from https://www.unicode.org/Public/<version>/ucd/. No host Unicode APIs are used.
"""

import argparse
import hashlib
from pathlib import Path

VERSIONS = ("14.0.0", "15.0.0", "15.1.0", "16.0.0", "17.0.0")
OUTPUT = Path(__file__).resolve().parents[1] / "Sources/Tokenizers/Core/UnicodeCompatibility.generated.swift"


def read_ucd(root, version):
    # Only normalization properties remain: category, combining class, decomposition,
    # and lowercase. Classification caches now come directly from the Swift runtime.
    records = [("Cn", "0", "", "")] * 0x110000
    data = (root / version / "UnicodeData.txt").read_bytes()
    provenance = f"// {version}/UnicodeData.txt: SHA-256 {hashlib.sha256(data).hexdigest()}"
    start = None
    for line in data.decode().splitlines():
        fields = line.split(";")
        value = int(fields[0], 16)
        record = (fields[2], fields[3], fields[5], fields[13])
        if fields[1].endswith(", First>"):
            start = value
        elif fields[1].endswith(", Last>"):
            records[start:value + 1] = [record] * (value + 1 - start)
            start = None
        else:
            records[value] = record
    return records, [provenance]


def ranges(values):
    result = []
    for value in sorted(values):
        if result and result[-1] == value:
            result[-1] = value + 1
        else:
            result.extend((value, value + 1))
    return result


def array(name, values):
    lines = [f"    static let {name}: [UInt32] = ["]
    for start in range(0, len(values), 8):
        lines.append("        " + ", ".join(f"0x{v:08X}" for v in values[start:start + 8]) + ",")
    return "\n".join(lines + ["    ]"])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ucd-dir", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    baseline = None
    changed = set()
    supplementary = set()
    hashes = []
    for version in VERSIONS:
        records, provenance = read_ucd(args.ucd_dir, version)
        hashes.extend(provenance)
        if baseline is None:
            baseline = records
        changed.update(v for v in range(0x10000) if records[v] != baseline[v])
        supplementary.update(
            v for v in range(0x10000, 0x110000)
            if records[v][0].startswith("M") or records[v][1] != "0" or records[v][2] or records[v][3]
        )
        # Composition can consume letters with combining class zero (e.g. Kirat Rai),
        # not only marks. Every canonical decomposition component is conservative here;
        # excluding its first component would require a separate composition quick check.
        supplementary.update(
            int(part, 16)
            for record in records
            if record[2] and not record[2].startswith("<")
            for part in record[2].split()
            if int(part, 16) >= 0x10000
        )
    source = "// Generated by scripts/unicode_compatibility.py. Do not edit.\n"
    source += "// Unicode 14–17; ranges are sorted, disjoint [start, end) pairs.\n"
    source += "// Data: https://www.unicode.org/Public/ ; https://www.unicode.org/license.txt\n"
    source += "\n".join(hashes) + "\n\nenum UnicodeCompatibility {\n"
    source += f"    // {len(changed)} BMP scalars whose relevant properties differ between releases.\n"
    source += array("bmpRanges", ranges(changed)) + "\n\n"
    source += "    // Conservative union of supplementary scalars requiring normalization or case handling.\n"
    source += array("supplementaryRanges", ranges(supplementary)) + "\n}\n"
    if args.check:
        if OUTPUT.read_text() != source:
            raise SystemExit(f"{OUTPUT} is stale")
    else:
        OUTPUT.write_text(source)
    print(f"{len(changed)} BMP scalars, {len(ranges(supplementary)) // 2} supplementary ranges")


if __name__ == "__main__":
    main()
