// mlx-swift-lm consumes tokenizers through the code generated by its
// `#adaptHuggingFaceTokenizer` / `#huggingFaceTokenizerLoader` macros
// (Libraries/MLXHuggingFaceMacros/HuggingFaceIntegrationMacros.swift). This file replicates
// that generated code verbatim against a local copy of `MLXLMCommon.Tokenizer`, so any change
// to our public surface that would break the bridge fails to compile here first.

import Foundation
import Testing
import Tokenizers

// MARK: - Local replica of MLXLMCommon's protocol surface

private protocol MLXTokenizer: Sendable {
    func encode(text: String, addSpecialTokens: Bool) -> [Int]
    func decode(tokenIds: [Int], skipSpecialTokens: Bool) -> String
    func convertTokenToId(_ token: String) -> Int?
    func convertIdToToken(_ id: Int) -> String?

    var bosToken: String? { get }
    var eosToken: String? { get }
    var unknownToken: String? { get }

    func applyChatTemplate(
        messages: [[String: any Sendable]],
        tools: [[String: any Sendable]]?,
        additionalContext: [String: any Sendable]?
    ) throws -> [Int]
}

private enum MLXTokenizerError: Error {
    case missingChatTemplate
}

private protocol MLXTokenizerLoader: Sendable {
    func load(from directory: URL) async throws -> any MLXTokenizer
}

// MARK: - Verbatim macro expansions

/// `#adaptHuggingFaceTokenizer(upstream)`
private func adaptHuggingFaceTokenizer(_ huggingFaceTokenizer: any Tokenizers.Tokenizer) -> any MLXTokenizer {
    { (huggingFaceTokenizer: any Tokenizers.Tokenizer) -> any MLXTokenizer in
        struct TokenizerBridge: MLXTokenizer {
            private let upstream: any Tokenizers.Tokenizer

            init(_ upstream: any Tokenizers.Tokenizer) {
                self.upstream = upstream
            }

            func encode(text: String, addSpecialTokens: Bool) -> [Int] {
                upstream.encode(text: text, addSpecialTokens: addSpecialTokens)
            }

            // swift-transformers uses `decode(tokens:)` instead of `decode(tokenIds:)`.
            func decode(tokenIds: [Int], skipSpecialTokens: Bool) -> String {
                upstream.decode(tokens: tokenIds, skipSpecialTokens: skipSpecialTokens)
            }

            func convertTokenToId(_ token: String) -> Int? {
                upstream.convertTokenToId(token)
            }

            func convertIdToToken(_ id: Int) -> String? {
                upstream.convertIdToToken(id)
            }

            var bosToken: String? { upstream.bosToken }
            var eosToken: String? { upstream.eosToken }
            var unknownToken: String? { upstream.unknownToken }

            func applyChatTemplate(
                messages: [[String: any Sendable]],
                tools: [[String: any Sendable]]?,
                additionalContext: [String: any Sendable]?
            ) throws -> [Int] {
                do {
                    return try upstream.applyChatTemplate(
                        messages: messages, tools: tools, additionalContext: additionalContext)
                } catch Tokenizers.TokenizerError.missingChatTemplate {
                    throw MLXTokenizerError.missingChatTemplate
                }
            }
        }

        return TokenizerBridge(huggingFaceTokenizer)
    }(huggingFaceTokenizer)
}

/// `#huggingFaceTokenizerLoader()`
private func huggingFaceTokenizerLoader() -> any MLXTokenizerLoader {
    { () -> any MLXTokenizerLoader in
        struct TransformersLoader: MLXTokenizerLoader {
            public init() {}

            public func load(from directory: URL) async throws -> any MLXTokenizer {
                let upstream = try await Tokenizers.AutoTokenizer.from(modelFolder: directory)
                return adaptHuggingFaceTokenizer(upstream)
            }
        }

        return TransformersLoader()
    }()
}

// MARK: - Tests

@Suite("mlx-swift-lm bridge compatibility")
struct MLXBridgeCompatibilityTests {
    @Test("Bridge loads and drives a tokenizer end to end")
    func bridge() async throws {
        let folder = try await HubFixtures.modelFolder(for: "Qwen/Qwen3-0.6B")
        let tokenizer = try await huggingFaceTokenizerLoader().load(from: folder)

        let ids = tokenizer.encode(text: "Hello world", addSpecialTokens: true)
        #expect(!ids.isEmpty)
        #expect(tokenizer.decode(tokenIds: ids, skipSpecialTokens: true) == "Hello world")
        #expect(tokenizer.eosToken == "<|im_end|>")
        #expect(tokenizer.convertTokenToId("<|im_end|>") == 151645)
        #expect(tokenizer.convertIdToToken(151645) == "<|im_end|>")

        let prompt = try tokenizer.applyChatTemplate(
            messages: [["role": "user", "content": "Hi"]], tools: nil, additionalContext: nil
        )
        #expect(prompt.first == 151644)  // <|im_start|>
    }

    @Test("Missing chat template maps to the bridge error")
    func missingTemplate() async throws {
        let folder = try await HubFixtures.modelFolder(for: "google-bert/bert-base-uncased")
        let tokenizer = try await huggingFaceTokenizerLoader().load(from: folder)
        #expect(throws: MLXTokenizerError.self) {
            try tokenizer.applyChatTemplate(messages: [], tools: nil, additionalContext: nil)
        }
    }

    @Test("Vocabulary walk used by guided generation terminates and is dense")
    func vocabularyWalk() async throws {
        let tokenizer = try await HubFixtures.tokenizer(for: "Qwen/Qwen3-0.6B")
        var id = 0
        while tokenizer.convertIdToToken(id) != nil { id += 1 }
        #expect(id == 151669)
    }
}

@Suite("Concurrency")
struct ConcurrencyTests {
    @Test("Concurrent encodes produce identical results")
    func concurrentEncodes() async throws {
        let tokenizer = try await HubFixtures.tokenizer(for: "Qwen/Qwen3-0.6B")
        let texts = (0..<64).map { i in
            "Sample \(i): the quick brown fox jumps over the lazy dog \(i * 7) times — naïve café 東京 😀 <|im_start|>user\nhi<|im_end|>"
        }
        let expected = texts.map { tokenizer.encode(text: $0) }

        try await withThrowingTaskGroup(of: Void.self) { group in
            for _ in 0..<8 {
                group.addTask {
                    for (i, text) in texts.enumerated() {
                        let ids = tokenizer.encode(text: text)
                        guard ids == expected[i] else {
                            throw HubFixtures.FixtureError.unsupportedTokenizer
                        }
                    }
                }
            }
            try await group.waitForAll()
        }
    }
}
