// Verifies the checked-in run-length Unicode tables against the scalar properties of the
// running toolchain, and regenerates them on request.

import Foundation
import Testing

@testable import Tokenizers

@Suite("Unicode tables")
struct UnicodeTablesTests {
    static let generatedFile = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        .appendingPathComponent("Sources/Tokenizers/Core/UnicodeTables.generated.swift")

    @Test("Generated runs match the scalar properties of this toolchain")
    func tablesMatchProperties() throws {
        let flags = ScalarClassifier.computeBMP()
        let extraFlags = ScalarClassifier.computeBMPExtra()
        let runs = UnicodeTables.encode(flags: flags, extraFlags: extraFlags)

        if ProcessInfo.processInfo.environment["REGENERATE_UNICODE_TABLES"] == "1" {
            var source =
                "// Generated by `REGENERATE_UNICODE_TABLES=1 swift test --filter UnicodeTablesTests`. Do not edit.\n"
            source +=
                "// \(runs.count) runs over the Basic Multilingual Plane: start << 16 | flags << 8 | extraFlags.\n\n"
            source += "extension UnicodeTables {\n    static let runs: [UInt32] = [\n"
            for chunk in stride(from: 0, to: runs.count, by: 8) {
                let line = runs[chunk..<min(chunk + 8, runs.count)].map { String(format: "0x%08X", $0) }
                source += "        " + line.joined(separator: ", ") + ",\n"
            }
            source += "    ]\n}\n"
            try source.write(to: Self.generatedFile, atomically: true, encoding: .utf8)
        }

        let firstMismatch = zip(UnicodeTables.runs, runs).enumerated().first { $1.0 != $1.1 }?.offset
        #expect(
            UnicodeTables.runs.count == runs.count && firstMismatch == nil,
            "checked-in \(UnicodeTables.runs.count) runs vs computed \(runs.count), first mismatch at \(firstMismatch.map(String.init) ?? "-"): run `REGENERATE_UNICODE_TABLES=1 swift test --filter UnicodeTablesTests`"
        )
        #expect(ScalarClassifier.bmp.elementsEqual(flags))
        #expect(ScalarClassifier.bmpExtra.elementsEqual(extraFlags))
    }
}
